// Single source of truth for S3 key derivation, variant naming, and
// filename/folder validation. Used by the API routes, the worker, and the client.

export const VARIANT_WIDTHS = [640, 1280, 2880] as const;
export const VARIANT_FORMATS = ["jpg", "webp"] as const;

export type VariantWidth = (typeof VARIANT_WIDTHS)[number];
export type VariantFormat = (typeof VARIANT_FORMATS)[number];

// 128px variants were generated by earlier versions; keep them in the cleanup
// list so moves and deletes of old photos don't leave orphans behind.
const CLEANUP_WIDTHS = [128, ...VARIANT_WIDTHS];

export const VARIANT_SUFFIXES = CLEANUP_WIDTHS.flatMap((width) =>
  VARIANT_FORMATS.map((format) => `_${width}.${format}`)
);

/** "folder/photo.jpg" -> "folder/photo" */
export function baseKey(s3Key: string) {
  return s3Key.replace(/\.[^.]+$/, "");
}

/**
 * The stem a photo's variants hang off. Normally `baseKey`, but originals
 * written by the old web pipeline live at "<base>_original.<ext>" with their
 * variants at "<base>_<width>.<format>" — strip the marker so both schemes
 * address the same variant objects. Mirrors keys.rs `variant_base`.
 */
export function variantBase(s3Key: string) {
  return baseKey(s3Key).replace(/_original$/, "");
}

/**
 * The filename to show a user. Legacy web-pipeline originals are stored as
 * "<base>_original.<ext>"; the marker is an internal detail of the old variant
 * scheme, so hide it from anything the user reads. The extension is preserved.
 * Mirrors the suffix `variantBase` strips for key derivation.
 */
export function displayName(filename: string) {
  return filename.replace(/_original(\.[^.]+)?$/, "$1");
}

/** "folder/photo.jpg" -> "folder/photo_640.webp" */
export function variantKey(
  s3Key: string,
  width: VariantWidth,
  format: VariantFormat
) {
  return `${variantBase(s3Key)}_${width}.${format}`;
}

/** Percent-encode each path segment of an S3 key for use in a URL. */
export function encodeKey(s3Key: string) {
  return s3Key.split("/").map(encodeURIComponent).join("/");
}

/**
 * Strip any path components from a client-supplied filename and reject
 * anything that can't be a plain file name. Returns null when invalid.
 */
export function sanitizeFilename(filename: unknown): string | null {
  if (typeof filename !== "string") return null;
  const name = filename.split(/[/\\]/).pop()?.trim() ?? "";
  if (!name || name === "." || name === "..") return null;
  // eslint-disable-next-line no-control-regex -- reject control chars in names
  if (/[\x00-\x1f]/.test(name)) return null;
  return name;
}

/**
 * Folders are a single path segment (no nesting). Returns null when invalid.
 */
export function sanitizeFolder(folder: unknown): string | null {
  if (typeof folder !== "string") return null;
  const name = folder.trim();
  if (!name || name === "." || name === "..") return null;
  // eslint-disable-next-line no-control-regex -- reject control chars in names
  if (/[/\\\x00-\x1f]/.test(name)) return null;
  return name;
}
