import { describe, it, expect } from "vitest";
import { imageUrl, originalUrl, previewUrl } from "@/lib/image-url";

describe("image-url", () => {
  it("builds a photo:// URL for the default variant", () => {
    expect(imageUrl("inbox/photo.jpg")).toBe(
      "photo://localhost/inbox/photo_640.webp"
    );
  });

  it("builds correct variant keys for different resolutions and formats", () => {
    expect(imageUrl("folder/img.png", "1280", "jpg")).toBe(
      "photo://localhost/folder/img_1280.jpg"
    );
    expect(imageUrl("folder/img.png", "2880", "webp")).toBe(
      "photo://localhost/folder/img_2880.webp"
    );
  });

  it("percent-encodes special characters per path segment", () => {
    expect(imageUrl("my photos/café #1.jpg", "640", "webp")).toBe(
      "photo://localhost/my%20photos/caf%C3%A9%20%231_640.webp"
    );
  });

  it("strips the old-scheme _original marker when addressing variants", () => {
    // The old web pipeline stored originals at "<base>_original.jpg" with
    // variants at "<base>_<width>.<format>".
    expect(imageUrl("calella/R0007098_original.jpg", "640", "webp")).toBe(
      "photo://localhost/calella/R0007098_640.webp"
    );
    // A name that merely contains "original" elsewhere is untouched.
    expect(imageUrl("inbox/original_takes.jpg", "640", "webp")).toBe(
      "photo://localhost/inbox/original_takes_640.webp"
    );
  });

  it("never strips width markers — DSC_1280.jpg is a photo, not a derivative", () => {
    // Nikon/Canon counters produce names like DSC_1280.jpg; stripping the
    // suffix would collide its derivatives with a DSC_2880.jpg sibling.
    // Stand-in rows for original-less variant sets (cataloged under e.g.
    // "…_2880.jpg") likewise keep their full stem and get a fresh
    // derivative set generated by the refresh.
    expect(imageUrl("inbox/DSC_1280.jpg", "640", "webp")).toBe(
      "photo://localhost/inbox/DSC_1280_640.webp"
    );
    expect(imageUrl("copenhaguen/P1160508_2880.jpg", "640", "webp")).toBe(
      "photo://localhost/copenhaguen/P1160508_2880_640.webp"
    );
  });

  it("returns the original object URL untouched by variant naming", () => {
    expect(originalUrl("inbox/photo.jpg")).toBe(
      "photo://localhost/inbox/photo.jpg"
    );
  });

  it("builds a preview:// URL from an absolute local path, slashes encoded", () => {
    // The whole path (its own slashes included) is one encoded URL segment,
    // so the Rust handler can decode it back to the original absolute path.
    expect(previewUrl("/Users/jav/my photos/café #1.jpg")).toBe(
      "preview://localhost/%2FUsers%2Fjav%2Fmy%20photos%2Fcaf%C3%A9%20%231.jpg"
    );
  });
});
