//! Rust port of src/lib/keys.ts — the single source of truth for S3 key
//! derivation, variant naming, and filename/folder validation. Keep the two
//! in sync (same widths, same suffix scheme) so existing bucket content
//! stays valid.

pub const VARIANT_WIDTHS: [u32; 3] = [640, 1280, 2880];
pub const VARIANT_FORMATS: [VariantFormat; 2] = [VariantFormat::Jpg, VariantFormat::Webp];

/// 128px variants were generated by earlier versions; keep them in the
/// cleanup list so moves and deletes of old photos don't leave orphans.
const CLEANUP_WIDTHS: [u32; 4] = [128, 640, 1280, 2880];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VariantFormat {
    Jpg,
    Webp,
}

impl VariantFormat {
    pub fn ext(self) -> &'static str {
        match self {
            VariantFormat::Jpg => "jpg",
            VariantFormat::Webp => "webp",
        }
    }

    pub fn content_type(self) -> &'static str {
        match self {
            VariantFormat::Jpg => "image/jpeg",
            VariantFormat::Webp => "image/webp",
        }
    }
}

/// "folder/photo.jpg" -> "folder/photo". Mirrors the TS regex
/// `/\.[^.]+$/` — strips from the final dot only when at least one
/// character follows it.
pub fn base_key(s3_key: &str) -> &str {
    match s3_key.rfind('.') {
        Some(i) if i + 1 < s3_key.len() => &s3_key[..i],
        _ => s3_key,
    }
}

/// The stem a photo's variants hang off. Normally `base_key`, but originals
/// written by the old web pipeline live at "<base>_original.<ext>" with their
/// variants at "<base>_<width>.<fmt>" — strip the marker so both schemes
/// address the same variant objects.
pub fn variant_base(s3_key: &str) -> &str {
    let base = base_key(s3_key);
    base.strip_suffix("_original").unwrap_or(base)
}

/// "folder/photo.jpg" -> "folder/photo_640.webp"
pub fn variant_key(s3_key: &str, width: u32, format: VariantFormat) -> String {
    format!("{}_{}.{}", variant_base(s3_key), width, format.ext())
}

/// All suffixes a photo's variants may live under, for moves and deletes.
pub fn variant_suffixes() -> Vec<String> {
    CLEANUP_WIDTHS
        .iter()
        .flat_map(|width| {
            VARIANT_FORMATS
                .iter()
                .map(move |format| format!("_{}.{}", width, format.ext()))
        })
        .collect()
}

/// Strip any path components from a filename and reject anything that can't
/// be a plain file name.
pub fn sanitize_filename(filename: &str) -> Option<String> {
    let name = filename
        .split(['/', '\\'])
        .next_back()
        .unwrap_or("")
        .trim()
        .to_string();
    if name.is_empty() || name == "." || name == ".." {
        return None;
    }
    if name.chars().any(|c| ('\u{0}'..='\u{1f}').contains(&c)) {
        return None;
    }
    Some(name)
}

/// Folders are a single path segment (no nesting).
pub fn sanitize_folder(folder: &str) -> Option<String> {
    let name = folder.trim().to_string();
    if name.is_empty() || name == "." || name == ".." {
        return None;
    }
    if name
        .chars()
        .any(|c| c == '/' || c == '\\' || ('\u{0}'..='\u{1f}').contains(&c))
    {
        return None;
    }
    Some(name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn base_key_strips_the_final_extension() {
        assert_eq!(base_key("folder/photo.jpg"), "folder/photo");
        assert_eq!(base_key("folder/photo.x.jpg"), "folder/photo.x");
        assert_eq!(base_key("folder/photo"), "folder/photo");
        // Trailing dot has no extension characters after it — unchanged,
        // matching the TS regex
        assert_eq!(base_key("folder/photo."), "folder/photo.");
    }

    #[test]
    fn variant_key_matches_web_scheme() {
        assert_eq!(
            variant_key("folder/photo.jpg", 640, VariantFormat::Webp),
            "folder/photo_640.webp"
        );
        assert_eq!(
            variant_key("folder/photo.jpg", 2880, VariantFormat::Jpg),
            "folder/photo_2880.jpg"
        );
    }

    #[test]
    fn variant_base_strips_the_old_original_marker() {
        // Old web pipeline: original at "<base>_original.jpg", variants at
        // "<base>_<width>.<fmt>".
        assert_eq!(variant_base("calella/R0007098_original.jpg"), "calella/R0007098");
        assert_eq!(
            variant_key("calella/R0007098_original.jpg", 640, VariantFormat::Webp),
            "calella/R0007098_640.webp"
        );
        // Current scheme is untouched.
        assert_eq!(variant_base("inbox/photo.jpg"), "inbox/photo");
        // The marker only counts as a stem suffix, not anywhere in the name.
        assert_eq!(variant_base("inbox/original_takes.jpg"), "inbox/original_takes");
    }

    #[test]
    fn variant_suffixes_include_legacy_128() {
        let suffixes = variant_suffixes();
        assert_eq!(suffixes.len(), 8);
        assert!(suffixes.contains(&"_128.webp".to_string()));
        assert!(suffixes.contains(&"_2880.jpg".to_string()));
    }

    #[test]
    fn sanitize_filename_strips_paths_and_rejects_bad_names() {
        assert_eq!(sanitize_filename("/tmp/a/photo.jpg"), Some("photo.jpg".into()));
        assert_eq!(sanitize_filename("c:\\x\\photo.jpg"), Some("photo.jpg".into()));
        assert_eq!(sanitize_filename("  photo.jpg  "), Some("photo.jpg".into()));
        assert_eq!(sanitize_filename(""), None);
        assert_eq!(sanitize_filename("."), None);
        assert_eq!(sanitize_filename(".."), None);
        assert_eq!(sanitize_filename("bad\u{1}name"), None);
    }

    #[test]
    fn sanitize_folder_rejects_nesting() {
        assert_eq!(sanitize_folder("inbox"), Some("inbox".into()));
        assert_eq!(sanitize_folder(" trips "), Some("trips".into()));
        assert_eq!(sanitize_folder("a/b"), None);
        assert_eq!(sanitize_folder(".."), None);
        assert_eq!(sanitize_folder(""), None);
    }
}
